@extends('errors.layout')
@section('code', '404')
@section('color', 'text-cyan-400')
@section('title', 'Page Not Found')
@section('description', 'The page you are looking for does not exist or has been moved.')
