[build]
buildCommand = "npm ci && npm run build"

[deploy]
deployCommand = "php artisan migrate --force && php artisan db:seed --force && php artisan db:seed --class=RolesAndPermissionsSeeder --force && php artisan optimize"
